<a href="https://colab.research.google.com/github/Sagar1566/Python/blob/main/Cluster_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as numpy
import pandas as pandas
import matplotlib.pyplot as plt


In [27]:
rainfall = numpy.random.randint(200,800,(4,5))
rainfall

array([[793, 350, 747, 273, 255],
       [635, 549, 335, 746, 713],
       [427, 212, 400, 258, 680],
       [311, 621, 469, 524, 205]])

In [28]:
temperature = numpy.random.randint(15,40,(4,5))
temperature

array([[36, 19, 25, 26, 24],
       [26, 26, 34, 17, 34],
       [21, 34, 37, 22, 31],
       [35, 22, 26, 23, 20]])

In [29]:
fertilizer = numpy.random.randint(15,40,(4,5))
fertilizer

array([[21, 25, 35, 32, 20],
       [24, 34, 27, 25, 16],
       [21, 21, 28, 31, 34],
       [33, 22, 20, 15, 21]])

In [30]:
soil = numpy.random.randint(200,800,(4,5))
soil

array([[221, 589, 578, 734, 531],
       [592, 247, 368, 558, 378],
       [638, 561, 510, 558, 222],
       [708, 514, 601, 755, 412]])

In [31]:
humidity = numpy.random.randint(40,90,(4,5))
humidity

array([[63, 60, 60, 82, 71],
       [58, 87, 63, 53, 40],
       [77, 41, 76, 70, 83],
       [89, 71, 48, 85, 51]])

In [32]:
market_demand = numpy.random.randint(40,90,(4,5))
market_demand

array([[44, 64, 89, 53, 74],
       [55, 71, 86, 61, 40],
       [71, 79, 78, 54, 64],
       [63, 54, 41, 65, 59]])

In [33]:
crop_price = numpy.random.randint(1000, 3000, (4, 5))
crop_price


array([[1984, 2195, 1400, 1408, 1379],
       [2281, 1642, 1540, 2408, 1560],
       [1613, 2702, 1070, 2917, 1484],
       [2546, 1300, 1164, 1563, 2439]])

In [34]:
df = pandas.DataFrame({
    "rainfall": rainfall.flatten(),
    "temperature": temperature.flatten(),
    "soil_moisture": soil.flatten(),
    "fertilizer": fertilizer.flatten(),
    "humidity": humidity.flatten(),
    "market_demand": market_demand.flatten(),
    "crop_price": crop_price.flatten()
})

In [35]:
df

rainfall  temperature  soil_moisture  fertilizer  humidity  market_demand  \
0        793           36            221          21        63             44   
1        350           19            589          25        60             64   
2        747           25            578          35        60             89   
3        273           26            734          32        82             53   
4        255           24            531          20        71             74   
5        635           26            592          24        58             55   
6        549           26            247          34        87             71   
7        335           34            368          27        63             86   
8        746           17            558          25        53             61   
9        713           34            378          16        40             40   
10       427           21            638          21        77             71   
11       212           34            561          21        41             79   
12       400           37            510          28        76             78   
13       258           22            558          31        70             54   
14       680           31            222          34        83             64   
15       311           35            708          33        89             63   
16       621           22            514          22        71             54   
17       469           26            601          20        48             41   
18       524           23            755          15        85             65   
19       205           20            412          21        51             59   

    crop_price  
0         1984  
1         2195  
2         1400  
3         1408  
4         1379  
5         2281  
6         1642  
7         1540  
8         2408  
9         1560  
10        1613  
11        2702  
12        1070  
13        2917  
14        1484  
15        2546  
16        1300  
17        1164  
18        1563  
19        2439

In [37]:
x= df.iloc[:,:-1].values

In [38]:
y= df.iloc[:,-1].values

In [39]:
x

array([[793,  36, 221,  21,  63,  44],
       [350,  19, 589,  25,  60,  64],
       [747,  25, 578,  35,  60,  89],
       [273,  26, 734,  32,  82,  53],
       [255,  24, 531,  20,  71,  74],
       [635,  26, 592,  24,  58,  55],
       [549,  26, 247,  34,  87,  71],
       [335,  34, 368,  27,  63,  86],
       [746,  17, 558,  25,  53,  61],
       [713,  34, 378,  16,  40,  40],
       [427,  21, 638,  21,  77,  71],
       [212,  34, 561,  21,  41,  79],
       [400,  37, 510,  28,  76,  78],
       [258,  22, 558,  31,  70,  54],
       [680,  31, 222,  34,  83,  64],
       [311,  35, 708,  33,  89,  63],
       [621,  22, 514,  22,  71,  54],
       [469,  26, 601,  20,  48,  41],
       [524,  23, 755,  15,  85,  65],
       [205,  20, 412,  21,  51,  59]])